# Ultralytics Actions 🚀, AGPL-3.0 License https://ultralytics.com/license

name: "Ultralytics CLA"
description: "Checks if contributors have signed the Ultralytics Contributor License Agreement"
inputs:
  github-token:
    description: "GitHub token"
    required: true
  repository:
    description: "GitHub repository name (including organization, e.g., 'org/repo')"
    required: true
  branch:
    description: "Branch to store CLA signatures"
    required: true
    default: "cla-signatures"
  path-to-signatures:
    description: "Path to the JSON file containing CLA signatures"
    required: true
    default: "signatures/version1/cla.json"
  cla-document-url:
    description: "URL to the CLA document"
    required: true
    default: "https://docs.ultralytics.com/help/CLA"
  allowlist:
    description: "Comma-separated list of users/bots to ignore"
    required: false
    default: "dependabot[bot],github-actions,bot*"
  pr-sign-comment:
    description: "Comment to trigger CLA signing"
    required: true
    default: "I have read the CLA Document and I sign the CLA"
  allsigned-prcomment:
    description: "Comment to post when all contributors have signed"
    required: true
    default: "All Contributors have signed the CLA. ✅"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ultralytics-action
      shell: bash

    - name: Check CLA
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        REPOSITORY: ${{ inputs.repository }}
        BRANCH: ${{ inputs.branch }}
        PATH_TO_SIGNATURES: ${{ inputs.path-to-signatures }}
        CLA_DOCUMENT_URL: ${{ inputs.cla-document-url }}
        ALLOWLIST: ${{ inputs.allowlist }}
        PR_SIGN_COMMENT: ${{ inputs.pr-sign-comment }}
        ALLSIGNED_PRCOMMENT: ${{ inputs.allsigned-prcomment }}
      run: ultralytics-actions-check-cla
      shell: bash
